title: 全栈开发工程师笔记
url: https://blog.jqknono.com
baseurl: ""
repository: jqknono/jqknono.github.io
description: 全栈开发的成长之路
encoding: utf-8
author:
  name: Cecil
  email: "jqknono@outlook.com"
safe: false
incremental: false
github: [metadata]
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "default"
#   - scope:
#       path: "/"
#     values:
#       layout: "default"
#   - scope:
#       path: "blog"
#     values:
#       layout: "default"
#   - scope:
#       path: "/blog"
#     values:
#       layout: "default"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
optional_front_matter:
  remove_originals: true
theme: minima
minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%Y-%b-%-d"

  # Generate social links in footer.
  #
  social_links:
    #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
    #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    - { platform: facebook, user_url: "https://www.facebook.com/jqknono" }
    #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github, user_url: "https://github.com/jqknono" }
    #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram, user_url: "https://www.instagram.com/jqknono" }
    #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    # - { platform: telegram, user_url: "https://t.me/jqknono" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/%E5%81%B2-%E6%9D%8E-8a938a149/",
      }
    #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    - {
        platform: stackoverflow,
        user_url: "https://stackoverflow.com/users/5329906/jqknono",
      }
    - { platform: twitter, user_url: "https://twitter.com/jqknono" }
    - { platform: youtube, user_url: "https://www.youtube.com/jqknono" }
# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md
  - cheetsheets.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true
disqus:
  shortname: jqknono
google_analytics: G-F3FFTG72NE
